name: Build Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"
          build-cache: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install build-essential cmake git clang libx11-dev -y

      - name: Configure
        run: xmake f --policies=build.ccache:y -y

      - name: Build
        run: xmake repo -u && xmake -vD -y

      - name: Show install error log
        if: failure()
        run: |
          find /home/runner/.xmake/cache -name install.txt -exec echo "==== {} ====" \; -exec cat {} \;
